server:
  port: 9001
spring:
  # 数据库配置
  datasource:
    name: khbyDB
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/khby?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  # 较高版本的 SpringBoot需要配置如下内容
  mvc:
    path match:
      matching-strategy: ant_path_matcher
