spring:
  application:
    name: service-first
  cloud:
    nacos:
      config:
        group: DEFAULT_GROUP
        server-addr: 192.168.66.101:8748
        namespace: d7108622-ab9b-408d-a113-2c96e0e2d85c
      discovery:
        server-addr: 192.168.66.101:8748
        namespace: d7108622-ab9b-408d-a113-2c96e0e2d85c
  config:
    import:
      - optional:nacos:application-dev.yml  # 监听 DEFAULT_GROUP:test.yml
knife4j:
  enable: true